// __DO NOT MODIFY THIS FILE MANUALLY__
// __THIS IS GENERATED BY RUNNING PROCESS_PLUGINS_JS.PY PRESENT IN 12X/V1__

/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2013 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/

// `JSLint` directives.
/*global define, window */
/*jslint devel: true, browser: true */

(function () {
    return (window.Ac.Plugins = {
  "rna_resource_url": window.location.origin,
  "types": {
    "tools": {
      "plugin_ids": [
        "home",
        "fillsign",
        "send_for_sign",
        "exportpdf",
        "createpdf",
        "send",
        "editpdf",
        "onboarding",
        "ob_preview",
        "walk_through",
        "digsig",
        "task_handler",
        "uss_search",
        "sign_services_auth",
        "unified_share",
        "oauthdialog"
      ],
      "default_plugin_id": "home"
    },
    "home_views": {
      "plugin_ids": [
        "sentfiles",
        "scan_files",
        "my_computer",
        "add_account",
        "activity_badge",
        "reviews",
        "signatures",
        "app_center",
        "receivedfiles"
      ],
      "default_plugin_id": "my_computer"
    },
    "search_views": {
      "plugin_ids": [
        "search_summary",
        "my_recent_files_search",
        "scan_files_search",
        "signatures_search",
        "my_computer_search",
        "sentfiles_search",
        "reviews_search"
      ],
      "default_plugin_id": "my_recent_files_search"
    },
    "full_preview": {
      "plugin_ids": [
        "exportpdf_rhp",
        "createpdf_rhp",
        "combineconvertpdf_rhp",
        "editpdf_rhp",
        "combinepdf_rhp",
        "pagesapp_rhp",
        "exportpdfupsellapp_rhp",
        "createpdfupsellapp_rhp",
        "redact_rhp",
        "protect_rhp",
        "optimize_rhp",
        "sign_services_auth"
      ],
      "default_plugin_id": "exportpdf_rhp"
    },
    "full_preview_rhp": {
      "plugin_ids": [
        "reviews",
        "signatures",
        "sentfiles"
      ]
    },
    "full_preview_overlays": {
      "plugin_ids": []
    },
    "file_selection_dlg": {
      "plugin_ids": [
        "my_recent_files_select",
        "my_computer_select",
        "add_account_select"
      ],
      "default_plugin_id": "my_recent_files_select"
    },
    "account_menu": {
      "ignore_selection": "True",
      "plugin_ids": []
    },
    "file_selection_actions": {
      "plugin_ids": [
        "selection_action_cpdf",
        "selection_action_epdf",
        "selection_action_ccpdf"
      ],
      "ignore_selection": "True"
    },
    "deep_link": {
      "plugin_ids": [],
      "no_selectors": "True"
    },
    "settings_dlg": {
      "plugin_ids": [
        "fillsign_settings"
      ],
      "default_plugin_id": "fillsign_settings"
    },
    "template": {
      "plugin_ids": [
        "my_files",
        "my_files_select",
        "desktop_connector_files",
        "desktop_connector_files_select"
      ],
      "ignore_selection": "True"
    }
  },
  "groups": {
    "blue_heron": {
      "config_url": "static/js/config.js",
      "base_url":window.location.origin,
      "home": {
        "selector_css_url": "static/js/plugins/home/css/main-selector.css",
        "selector_module_url": "acplugins/home/js/selector",
        "selector_class": "Ac.Plugins.Home.SelectorView",
        "plugin_css_url": "static/js/plugins/home/css/main.css",
        "plugin_module_url": "acplugins/home/js/plugin",
        "plugin_class": "Ac.Plugins.Home.PluginView",
        "load": "force"
      },
      "sign_services_auth": {
        "selector_css_url": "static/js/plugins/sign-services-auth/css/main-selector.css",
        "selector_module_url": "pdmplugins/sign-services-auth/js/selector",
        "selector_class": "Ac.Plugins.SignServicesAuth.SelectorView",
        "plugin_css_url": "static/js/plugins/sign-services-auth/css/main.css",
        "plugin_module_url": "pdmplugins/sign-services-auth/js/plugin",
        "plugin_class": "Ac.Plugins.SignServicesAuth.PluginView",
        "load": "force"
      },
      "uss_search": {
        "selector_css_url": "static/js/plugins/uss-search/css/main-selector.css",
        "selector_module_url": "acplugins/uss-search/js/selector",
        "selector_class": "Ac.Plugins.USSSearch.SelectorView",
        "plugin_css_url": "static/js/plugins/uss-search/css/main.css",
        "plugin_module_url": "acplugins/uss-search/js/plugin",
        "plugin_class": "Ac.Plugins.USSSearch.PluginView",
        "load": "lazy"
      },
      "my_files": {
        "selector_module_url": "acplugins/my-files/js/selector",
        "selector_class": "Ac.Plugins.MyFiles.SelectorView",
        "plugin_module_url": "acplugins/my-files/js/plugin",
        "plugin_class": "Ac.Plugins.MyFiles.PluginView",
        "load": "force",
        "section": "FILE_LISTS_SEARCH"
      },
      "my_files_select": {
        "selector_module_url": "acplugins/my-files/js/selector",
        "selector_class": "Ac.Plugins.MyFiles.SelectorView",
        "plugin_module_url": "acplugins/my-files-select/js/plugin",
        "plugin_class": "Ac.Plugins.MyFilesSelect.PluginView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "my_recent_files_select": {
        "selector_module_url": "acplugins/my-recent-files/js/selector",
        "selector_class": "Ac.Plugins.MyRecentFiles.SelectorView",
        "plugin_module_url": "acplugins/my-recent-files-select/js/plugin",
        "plugin_class": "Ac.Plugins.MyRecentFilesSelect.PluginView",
        "load": "lazy"
      },
      "my_recent_files_search": {
        "selector_module_url": "acplugins/my-recent-files/js/selector",
        "selector_class": "Ac.Plugins.MyRecentFiles.SelectorView",
        "plugin_module_url": "acplugins/my-recent-files/js/plugin",
        "plugin_class": "Ac.Plugins.MyRecentFiles.PluginView",
        "load": "lazy",
        "search_scope": "recent"
      },
      "add_account": {
        "selector_css_url": "static/js/plugins/add-account/css/main-selector.css",
        "selector_module_url": "acplugins/add-account/js/selector",
        "selector_class": "Ac.Plugins.AddAccount.SelectorView",
        "plugin_css_url": "static/js/plugins/add-account/css/main.css",
        "plugin_module_url": "acplugins/add-account/js/plugin",
        "plugin_class": "Ac.Plugins.AddAccount.PluginView",
        "load": "lazy",
        "section": "FILE_LISTS"
      },
      "add_account_select": {
        "selector_css_url": "static/js/plugins/add-account/css/main-selector.css",
        "selector_module_url": "acplugins/add-account/js/selector",
        "selector_class": "Ac.Plugins.AddAccount.SelectorView",
        "plugin_css_url": "static/js/plugins/add-account-select/css/main.css",
        "plugin_module_url": "acplugins/add-account-select/js/plugin",
        "plugin_class": "Ac.Plugins.AddAccountSelect.PluginView",
        "load": "lazy",
        "section": "FILE_LISTS"
      },
      "send": {
        "selector_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/tool-selector.css",
        "selector_module_url": "acplugins/tracked-send/js/tool/selector",
        "selector_class": "Ac.Plugins.TrackedSend.Tool.ToolSelectorView",
        "plugin_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/tool-view.css",
        "plugin_module_url": "acplugins/tracked-send/js/tool/plugin",
        "plugin_class": "Ac.Plugins.TrackedSend.Tool.ToolView",
        "load": "lazy"
      }
    },
    "pdm": {
      "config_url": "static/js/config.js",
      "analytics_url": "static/js/desktop.js",
      "base_url": window.location.origin,
      "my_computer": {
        "selector_css_url": "static/js/plugins/my-computer/css/main-selector.css",
        "selector_module_url": "pdmplugins/my-computer/js/selector",
        "selector_class": "Ac.Plugins.MyComputer.SelectorView",
        "plugin_css_url": "static/js/plugins/my-computer/css/main.css",
        "plugin_module_url": "pdmplugins/my-computer/js/plugin",
        "plugin_class": "Ac.Plugins.MyComputer.PluginView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "my_computer_search": {
        "selector_css_url": "static/js/plugins/my-computer/css/main-selector.css",
        "selector_module_url": "pdmplugins/my-computer/js/selector",
        "selector_class": "Ac.Plugins.MyComputer.SelectorView",
        "plugin_css_url": "static/js/plugins/my-computer/css/main.css",
        "plugin_module_url": "pdmplugins/my-computer/js/plugin",
        "plugin_class": "Ac.Plugins.MyComputer.PluginView",
        "section": "SHARED_DOCUMENTS"
      },
      "search_summary": {
        "selector_css_url": "static/js/plugins/search-summary/css/main-selector.css",
        "selector_module_url": "pdmplugins/search-summary/js/selector",
        "selector_class": "Ac.Plugins.SearchSummary.SelectorView",
        "plugin_css_url": "static/js/plugins/search-summary/css/main.css",
        "plugin_module_url": "pdmplugins/search-summary/js/plugin",
        "plugin_class": "Ac.Plugins.SearchSummary.PluginView",
        "load": "lazy"
      },
      "my_computer_select": {
        "selector_css_url": "static/js/plugins/my-computer-select/css/main-selector.css",
        "selector_module_url": "pdmplugins/my-computer-select/js/selector",
        "selector_class": "Ac.Plugins.MyComputerSelect.SelectorView",
        "plugin_css_url": "static/js/plugins/my-computer-select/css/main.css",
        "plugin_module_url": "pdmplugins/my-computer-select/js/plugin",
        "plugin_class": "Ac.Plugins.MyComputerSelect.PluginView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "sentfiles": {
        "selector_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-selector.css",
        "selector_module_url": "acplugins/tracked-send/js/home-view/selector",
        "selector_class": "Ac.Plugins.TrackedSend.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-view.css",
        "plugin_module_url": "acplugins/tracked-send/js/home-view/plugin",
        "plugin_class": "Ac.Plugins.TrackedSend.Home.HomeViewView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "receivedfiles": {
        "selector_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-selector.css",
        "selector_module_url": "acplugins/tracked-send/js/home-view/selector",
        "selector_class": "Ac.Plugins.TrackedSend.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-view.css",
        "plugin_module_url": "acplugins/tracked-send/js/home-view/plugin",
        "plugin_class": "Ac.Plugins.TrackedSend.Home.HomeViewView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "sentfiles_search": {
        "selector_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-selector.css",
        "selector_module_url": "acplugins/tracked-send/js/home-view/selector",
        "selector_class": "Ac.Plugins.TrackedSend.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-view.css",
        "plugin_module_url": "acplugins/tracked-send/js/home-view/plugin",
        "plugin_class": "Ac.Plugins.TrackedSend.Home.HomeViewView",
        "load": "lazy",
        "section": "FILE_LISTS_SEARCH",
        "search_scope": "parcel"
      },
      "scan_files": {
        "selector_css_url": "static/js/plugins/scan-files/css/main-selector.css",
        "selector_module_url": "acplugins/scan-files/js/selector",
        "selector_class": "Ac.Plugins.ScanFiles.SelectorView",
        "plugin_css_url": "static/js/plugins/scan-files/css/main.css",
        "plugin_module_url": "acplugins/scan-files/js/plugin",
        "plugin_class": "Ac.Plugins.ScanFiles.PluginView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "scan_files_search": {
        "selector_css_url": "static/js/plugins/scan-files/css/main-selector.css",
        "selector_module_url": "acplugins/scan-files/js/selector",
        "selector_class": "Ac.Plugins.ScanFiles.SelectorView",
        "plugin_css_url": "static/js/plugins/scan-files/css/main.css",
        "plugin_module_url": "acplugins/scan-files/js/plugin",
        "plugin_class": "Ac.Plugins.ScanFiles.PluginView",
        "section": "FILE_LISTS_SEARCH"
      },
      "exportpdf_rhp": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/rhp/exportpdf-rna-selector",
        "selector_class": "AiC.ExportPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/rhp/exportpdf-rna-tool-view",
        "plugin_class": "AiC.ExportPDF.ToolView",
        "load": "lazy"
      },
      "combineconvertpdf_rhp": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/rhp/combineconvertpdf-rna-selector",
        "selector_class": "AiC.CombineConvertPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/rhp/combineconvertpdf-rna-tool-view",
        "plugin_class": "AiC.CombineConvertPDF.ToolView",
        "load": "lazy"
      },
      "exportpdf": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/exportpdf-selector",
        "selector_class": "AiC.ExportPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/exportpdf-tool-view",
        "plugin_class": "AiC.ExportPDF.ToolView",
        "load": "lazy"
      },
      "createpdf": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/convertpdf-selector",
        "selector_class": "AiC.ConvertPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/convertpdf-tool-view",
        "plugin_class": "AiC.ConvertPDF.ToolView",
        "load": "lazy"
      },
      "createpdf_rhp": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/rhp/convertpdf-rna-selector",
        "selector_class": "AiC.ConvertPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/rhp/convertpdf-rna-tool-view",
        "plugin_class": "AiC.ConvertPDF.ToolView",
        "load": "lazy"
      },
      "combinepdf_rhp": {
        "selector_css_url": "static/js/plugins/combinepdf/css/main-selector.css",
        "selector_module_url": "acplugins/combinepdf/js/plugins/rhp/combinepdf-selector",
        "selector_class": "Ac.Plugins.CombinePDF.SelectorView",
        "plugin_css_url": "static/js/plugins/combinepdf/css/main.css",
        "plugin_module_url": "acplugins/combinepdf/js/plugins/rhp/combinepdf-tool-view",
        "plugin_class": "Ac.Plugins.CombinePDF.ToolView",
        "load": "lazy"
      },
      "redact_rhp": {
        "selector_css_url": "static/js/plugins/generic-rhp-app/css/main-selector.css",
        "selector_module_url": "acplugins/generic-rhp-app/js/plugins/rhp/generic-rhp-app-tool-view",
        "selector_class": "Ac.Plugins.GenericRhpApp.SelectorView",
        "plugin_css_url": "static/js/plugins/generic-rhp-app/css/main.css",
        "plugin_module_url": "acplugins/generic-rhp-app/js/plugins/rhp/generic-rhp-app-tool-view",
        "plugin_class": "Ac.Plugins.GenericRhpApp.ToolView",
        "load": "lazy"
      },
      "protect_rhp": {
        "selector_css_url": "static/js/plugins/generic-rhp-app/css/main-selector.css",
        "selector_module_url": "acplugins/generic-rhp-app/js/plugins/rhp/generic-rhp-app-tool-view",
        "selector_class": "Ac.Plugins.GenericRhpApp.SelectorView",
        "plugin_css_url": "static/js/plugins/generic-rhp-app/css/main.css",
        "plugin_module_url": "acplugins/generic-rhp-app/js/plugins/rhp/generic-rhp-app-tool-view",
        "plugin_class": "Ac.Plugins.GenericRhpApp.ToolView",
        "load": "lazy"
      },
      "optimize_rhp": {
        "selector_css_url": "static/js/plugins/generic-rhp-app/css/main-selector.css",
        "selector_module_url": "acplugins/generic-rhp-app/js/plugins/rhp/generic-rhp-app-selector",
        "selector_class": "Ac.Plugins.GenericRhpApp.SelectorView",
        "plugin_css_url": "static/js/plugins/generic-rhp-app/css/main.css",
        "plugin_module_url": "acplugins/generic-rhp-app/js/plugins/rhp/generic-rhp-app-tool-view",
        "plugin_class": "Ac.Plugins.GenericRhpApp.ToolView",
        "load": "lazy"
      },
      "pagesapp_rhp": {
        "selector_css_url": "static/js/plugins/pages-app/css/main-selector.css",
        "selector_module_url": "acplugins/pages-app/js/plugins/rhp/pages-app-selector",
        "selector_class": "Ac.Plugins.PagesApp.SelectorView",
        "plugin_css_url": "static/js/plugins/pages-app/css/main.css",
        "plugin_module_url": "acplugins/pages-app/js/plugins/rhp/pages-app-tool-view",
        "plugin_class": "Ac.Plugins.PagesApp.ToolView",
        "load": "lazy"
      },
      "exportpdfupsellapp_rhp": {
        "selector_css_url": "static/js/plugins/exportpdfupsell-app/css/main-selector.css",
        "selector_module_url": "acplugins/exportpdfupsell-app/js/plugins/rhp/exportpdfupsell-app-selector",
        "selector_class": "Ac.Plugins.ExportpdfupsellApp.SelectorView",
        "plugin_css_url": "static/js/plugins/exportpdfupsell-app/css/main.css",
        "plugin_module_url": "acplugins/exportpdfupsell-app/js/plugins/rhp/exportpdfupsell-app-tool-view",
        "plugin_class": "Ac.Plugins.ExportpdfupsellApp.ToolView",
        "load": "lazy"
      },
      "createpdfupsellapp_rhp": {
        "selector_css_url": "static/js/plugins/createspdfupsell-app/css/main-selector.css",
        "selector_module_url": "acplugins/createpdfupsell-app/js/plugins/rhp/createpdfupsell-app-selector",
        "selector_class": "Ac.Plugins.CreatepdfupsellApp.SelectorView",
        "plugin_css_url": "static/js/plugins/createpdfupsell-app/css/main.css",
        "plugin_module_url": "acplugins/createpdfupsell-app/js/plugins/rhp/createpdfupsell-app-tool-view",
        "plugin_class": "Ac.Plugins.CreatepdfupsellApp.ToolView",
        "load": "lazy"
      },
      "editpdf": {
        "selector_css_url": "static/js/plugins/editpdf/css/main-selector.css",
        "selector_module_url": "acplugins/editpdf/js/plugins/editpdf-selector",
        "selector_class": "Ac.Plugins.EditPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/editpdf/css/main.css",
        "plugin_module_url": "acplugins/editpdf/js/plugins/editpdf-tool-view",
        "plugin_class": "Ac.Plugins.EditPDF.ToolView",
        "load": "lazy"
      },
      "editpdf_rhp": {
        "selector_css_url": "static/js/plugins/editpdf/css/main-selector.css",
        "selector_module_url": "acplugins/editpdf/js/plugins/rhp/editpdf-selector",
        "selector_class": "Ac.Plugins.EditPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/editpdf/css/main.css",
        "plugin_module_url": "acplugins/editpdf/js/plugins/rhp/editpdf-tool-view",
        "plugin_class": "Ac.Plugins.EditPDF.ToolView",
        "load": "lazy"
      },
      "fillsign": {
        "selector_css_url": "static/js/plugins/fss/css/faf-main.css",
        "selector_module_url": "fss/js/faf-main",
        "selector_class": "Ac.Plugins.Faf.SelectorView",
        "plugin_css_url": "static/js/plugins/fss/css/faf-main.css",
        "plugin_module_url": "fss/js/faf-main",
        "plugin_class": "Ac.Plugins.Faf.ContentView",
        "load": "lazy"
      },
      "fillsign_settings": {
        "selector_module_url": "fss/js/faf-main",
        "selector_class": "Ac.Plugins.Faf.Settings.SelectorView",
        "plugin_css_url": "static/js/plugins/fss/js/plugins/css/faf-settings.css",
        "plugin_module_url": "fss/js/faf-main",
        "plugin_class": "Ac.Plugins.Faf.Settings.PluginView",
        "load": "lazy"
      },
      "send_for_sign": {
        "selector_css_url": "static/js/plugins/send-for-sign/css/main-selector.css",
        "selector_module_url": "pdmplugins/send-for-sign/js/selector",
        "selector_class": "Ac.Plugins.SendForSign.SelectorView",
        "plugin_css_url": "static/js/plugins/send-for-sign/css/main.css",
        "plugin_module_url": "pdmplugins/send-for-sign/js/plugin",
        "plugin_class": "Ac.Plugins.SendForSign.PluginView",
        "load": "lazy"
      },
      "unified_share": {
        "selector_css_url": "static/js/plugins/unified-share/css/main-selector.css",
        "selector_module_url": "pdmplugins/unified-share/js/selector",
        "selector_class": "Ac.Plugins.UnifiedShare.SelectorView",
        "plugin_css_url": "static/js/plugins/unified-share/css/main.css",
        "plugin_module_url": "pdmplugins/unified-share/js/plugin",
        "plugin_class": "Ac.Plugins.UnifiedShare.PluginView",
        "load": "force"
      },
      "oauthdialog": {
        "selector_css_url" : "static/js/plugins/oauthdialog/css/main-selector.css",
        "selector_module_url" : "pdmplugins/oauthdialog/js/selector",
        "selector_class" : "Ac.Plugins.OauthDialog.SelectorView",
        "plugin_css_url" : "static/js/plugins/oauthdialog/css/main.css",
        "plugin_module_url" : "pdmplugins/oauthdialog/js/plugin",
        "plugin_class" : "Ac.Plugins.OauthDialog.PluginView",
        "load" : "force"
     },
      "desktop_connector_files": {
        "selector_css_url": "static/js/plugins/desktop-connector-files/css/main-selector.css",
        "selector_module_url": "pdmplugins/desktop-connector-files/js/selector",
        "selector_class": "Ac.Plugins.DesktopConnectorFiles.SelectorView",
        "plugin_css_url": "static/js/plugins/desktop-connector-files/css/main.css",
        "plugin_module_url": "pdmplugins/desktop-connector-files/js/plugin",
        "plugin_class": "Ac.Plugins.DesktopConnectorFiles.PluginView",
        "load": "force",
        "section": "SHARED_DOCUMENTS"
      },
      "desktop_connector_files_select": {
        "selector_css_url": "static/js/plugins/desktop-connector-files-select/css/main-selector.css",
        "selector_module_url": "pdmplugins/desktop-connector-files-select/js/selector",
        "selector_class": "Ac.Plugins.DesktopConnectorFilesSelect.SelectorView",
        "plugin_css_url": "static/js/plugins/desktop-connector-files-select/css/main.css",
        "plugin_module_url": "pdmplugins/desktop-connector-files-select/js/plugin",
        "plugin_class": "Ac.Plugins.DesktopConnectorFilesSelect.PluginView",
        "load": "force",
        "section": "FILE_LISTS"
      },
      "selection_action_cpdf": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/selection-action-plugins/cpdf/selector",
        "selector_class": "Ac.Plugins.SelectionActionCPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/selection-action-plugins/cpdf/plugin",
        "plugin_class": "Ac.Plugins.SelectionActionCPDF.PluginView"
      },
      "selection_action_epdf": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/selection-action-plugins/epdf/selector",
        "selector_class": "Ac.Plugins.SelectionActionEPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/selection-action-plugins/epdf/plugin",
        "plugin_class": "Ac.Plugins.SelectionActionEPDF.PluginView"
      },
      "selection_action_ccpdf": {
        "selector_css_url": "static/js/plugins/aicuc/css/plugin-selectors.css",
        "selector_module_url": "aictools/plugins/selection-action-plugins/ccpdf/selector",
        "selector_class": "Ac.Plugins.SelectionActionCCPDF.SelectorView",
        "plugin_css_url": "static/js/plugins/aicuc/css/main.css",
        "plugin_module_url": "aictools/plugins/selection-action-plugins/ccpdf/plugin",
        "plugin_class": "Ac.Plugins.SelectionActionCCPDF.PluginView"
      },
      "ob_preview": {
        "selector_css_url": "static/js/plugins/ob-preview/css/main-selector.css",
        "selector_module_url": "acplugins/ob-preview/js/selector",
        "selector_class": "Ac.Plugins.ObPreview.SelectorView",
        "plugin_css_url": "static/js/plugins/ob-preview/css/main.css",
        "plugin_module_url": "acplugins/ob-preview/js/plugin",
        "plugin_class": "Ac.Plugins.ObPreview.PluginView",
        "load": "lazy"
      },
      "onboarding": {
        "selector_css_url": "static/js/plugins/on-boarding/css/main-selector.css",
        "selector_module_url": "acplugins/on-boarding/js/selector",
        "selector_class": "Ac.Plugins.OnBoarding.SelectorView",
        "plugin_css_url": "static/js/plugins/on-boarding/css/main.css",
        "plugin_module_url": "acplugins/on-boarding/js/plugin",
        "plugin_class": "Ac.Plugins.OnBoarding.PluginView",
        "load": "lazy"
      },
      "walk_through": {
        "selector_css_url": "static/js/plugins/walk-through/css/main-selector.css",
        "selector_module_url": "acplugins/walk-through/js/selector",
        "selector_class": "Ac.Plugins.WalkThrough.SelectorView",
        "plugin_css_url": "static/js/plugins/walk-through/css/main.css",
        "plugin_module_url": "acplugins/walk-through/js/plugin",
        "plugin_class": "Ac.Plugins.WalkThrough.PluginView",
        "load": "lazy"
      },
      "digsig": {
        "selector_css_url": "static/js/plugins/digsig/css/main-selector.css",
        "selector_module_url": "digsig/js/selector",
        "selector_class": "Ac.Plugins.DigSig.SelectorView",
        "plugin_css_url": "static/js/plugins/digsig/css/main.css",
        "plugin_module_url": "digsig/js/plugin",
        "plugin_class": "Ac.Plugins.DigSig.PluginView",
        "load": "lazy"
      },
      "activity_badge": {
        "selector_css_url": "static/js/plugins/activity-badge/css/main-selector.css",
        "selector_module_url": "pdmplugins/activity-badge/js/selector",
        "selector_class": "Ac.Plugins.ActivityBadge.SelectorView",
        "plugin_css_url": "static/js/plugins/activity-badge/css/main.css",
        "plugin_module_url": "pdmplugins/activity-badge/js/plugin",
        "plugin_class": "Ac.Plugins.ActivityBadge.PluginView",
        "load": "lazy"
      },
      "reviews": {
        "selector_css_url": "",
        "selector_module_url": "acplugins/reviews/js/selector",
        "selector_class": "Ac.Plugins.Reviews.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/reviews/css/main.css",
        "plugin_module_url": "acplugins/reviews/js/plugin",
        "plugin_class": "Ac.Plugins.Reviews.Home.HomeViewView",
        "load": "force",
        "section": "SHARED_DOCUMENTS"
      },
      "reviews_search": {
        "selector_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-selector.css",
        "selector_module_url": "acplugins/tracked-send/js/home-view/selector",
        "selector_class": "Ac.Plugins.TrackedSend.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/tracked-send/js/plugins/tracked-send/css/home-view.css",
        "plugin_module_url": "acplugins/tracked-send/js/home-view/plugin",
        "plugin_class": "Ac.Plugins.TrackedSend.Home.HomeViewView",
        "load": "force",
        "section": "FILE_LISTS_SEARCH",
        "search_scope": "review"
      },
      "signatures": {
        "selector_css_url": "",
        "selector_module_url": "acplugins/signatures/js/selector",
        "selector_class": "Ac.Plugins.Signatures.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/signatures/css/main.css",
        "plugin_module_url": "acplugins/signatures/js/plugin",
        "plugin_class": "Ac.Plugins.Signatures.Home.HomeViewView",
        "load": "force",
        "section": "SHARED_DOCUMENTS"
      },
      "signatures_search": {
        "selector_css_url": "",
        "selector_module_url": "acplugins/signatures/js/selector",
        "selector_class": "Ac.Plugins.Signatures.Home.HomeSelectorView",
        "plugin_css_url": "static/js/plugins/signatures/css/main.css",
        "plugin_module_url": "acplugins/signatures/js/plugin",
        "plugin_class": "Ac.Plugins.Signatures.Home.HomeViewView",
        "load": "force",
        "search_scope": "sign",
        "section": "ENTERPRISE_SIGN_SEARCH"
      },
      "app_center": {
        "selector_css_url": "static/js/plugins/app-center/css/main-selector.css",
        "selector_module_url": "acplugins/app-center/js/selector",
        "selector_class": "Ac.Plugins.AppCenter.SelectorView",
        "plugin_css_url": "static/js/plugins/app-center/css/main.css",
        "plugin_module_url": "acplugins/app-center/js/plugin",
        "plugin_class": "Ac.Plugins.AppCenter.PluginView",
        "load": "lazy"
      },
      "task_handler": {
        "selector_css_url": "static/js/plugins/task-handler/css/main-selector.css",
        "selector_module_url": "acplugins/task-handler/js/selector",
        "selector_class": "Ac.Plugins.TaskHandler.SelectorView",
        "plugin_css_url": "static/js/plugins/task-handler/css/main.css",
        "plugin_module_url": "acplugins/task-handler/js/plugin",
        "plugin_class": "Ac.Plugins.TaskHandler.PluginView",
        "load": "lazy"
      }
    }
  }
});
}());
