# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import http_pb2 as http__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emetadata.proto\x12\x0bSpacebridge\x1a\nhttp.proto\"\x1f\n\x1dGetSpacebridgeMetadataRequest\"|\n\x1eGetSpacebridgeMetadataResponse\x12\'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x16.Spacebridge.HttpErrorH\x00\x12\x12\n\x08instance\x18\x02 \x01(\x0cH\x00\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x42\n\n\x08responseB{\n/com.splunk.mobile.spacebridge.messages.metadataP\x01ZFcd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/spacebridgeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n/com.splunk.mobile.spacebridge.messages.metadataP\001ZFcd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/spacebridge'
  _GETSPACEBRIDGEMETADATAREQUEST._serialized_start=43
  _GETSPACEBRIDGEMETADATAREQUEST._serialized_end=74
  _GETSPACEBRIDGEMETADATARESPONSE._serialized_start=76
  _GETSPACEBRIDGEMETADATARESPONSE._serialized_end=200
# @@protoc_insertion_point(module_scope)
