# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sb_common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsb_common.proto\x12\x0bSpacebridge\"\xd1\x02\n\x0eSignedEnvelope\x12<\n\x0bmessageType\x18\x01 \x01(\x0e\x32\'.Spacebridge.SignedEnvelope.MessageType\x12\x12\n\nserialized\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"\xd9\x01\n\x0bMessageType\x12\x18\n\x14MESSAGE_TYPE_INVALID\x10\x00\x12$\n MESSAGE_TYPE_APPLICATION_MESSAGE\x10\x01\x12$\n MESSAGE_TYPE_SPACEBRIDGE_MESSAGE\x10\x02\x12%\n!MESSAGE_TYPE_NOTIFICATION_MESSAGE\x10\x03\x12\x14\n\x10MESSAGE_TYPE_ACK\x10\x04\x12\'\n#MESSAGE_TYPE_APPLICATION_MESSAGE_V2\x10\x05\"\xa8\x04\n\x18MdmAuthenticationRequest\x12\x19\n\x11\x63lientCredentials\x18\x01 \x01(\x0c\x12\x14\n\x0cmdmSignature\x18\x02 \x01(\x0c\x12\x17\n\x0f\x63lientSignature\x18\x03 \x01(\x0c\x1a\x9a\x02\n\x11\x43redentialsBundle\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x1b\n\x13publicKeyForSigning\x18\x03 \x01(\x0c\x12\x1e\n\x16publicKeyForEncryption\x18\x04 \x01(\x0c\x12\x1d\n\x15registrationAttemptId\x18\x05 \x01(\t\x12\x18\n\x10registeringAppId\x18\x06 \x01(\t\x12\x11\n\tloginType\x18\x07 \x01(\t\x12\x14\n\x0csessionToken\x18\x08 \x01(\t\x12\"\n\x1aregisteringAppFriendlyName\x18\t \x01(\t\x12\x1e\n\x16registeringAppPlatform\x18\n \x01(\t\x1a\xa4\x01\n\x11\x43lientCredentials\x12=\n\x13registrationVersion\x18\x01 \x01(\x0e\x32 .Spacebridge.RegistrationVersion\x12\x19\n\x11registrarClientId\x18\x02 \x01(\x0c\x12\"\n\x1a\x65ncryptedCredentialsBundle\x18\x03 \x01(\x0c\x12\x11\n\tcreatedAt\x18\x04 \x01(\x03*S\n\x13RegistrationVersion\x12 \n\x1cREGISTRATION_VERSION_INVALID\x10\x00\x12\x1a\n\x16REGISTRATION_VERSION_1\x10\x01\x42y\n-com.splunk.mobile.spacebridge.messages.commonP\x01ZFcd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/spacebridgeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sb_common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n-com.splunk.mobile.spacebridge.messages.commonP\001ZFcd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/spacebridge'
  _REGISTRATIONVERSION._serialized_start=927
  _REGISTRATIONVERSION._serialized_end=1010
  _SIGNEDENVELOPE._serialized_start=33
  _SIGNEDENVELOPE._serialized_end=370
  _SIGNEDENVELOPE_MESSAGETYPE._serialized_start=153
  _SIGNEDENVELOPE_MESSAGETYPE._serialized_end=370
  _MDMAUTHENTICATIONREQUEST._serialized_start=373
  _MDMAUTHENTICATIONREQUEST._serialized_end=925
  _MDMAUTHENTICATIONREQUEST_CREDENTIALSBUNDLE._serialized_start=476
  _MDMAUTHENTICATIONREQUEST_CREDENTIALSBUNDLE._serialized_end=758
  _MDMAUTHENTICATIONREQUEST_CLIENTCREDENTIALS._serialized_start=761
  _MDMAUTHENTICATIONREQUEST_CLIENTCREDENTIALS._serialized_end=925
# @@protoc_insertion_point(module_scope)
