/***************************************************************************************************
Copyright © Microsoft Corporation.  All rights reserved.

Synopsis:
    This file provides cleanup of classes added to a target in the course of setup.  
    
    DEPENDENCIES: none

***************************************************************************************************/

// NOTE: Do not use #pragma autorecover, or an autorecovery will also mofcomp this mof file!

#pragma namespace("\\\\.\\root\\Microsoft\\PolicyPlatform\\Documents")
#pragma namespace("\\\\.\\root\\Microsoft\\PolicyPlatform\\Documents\\Local")

#pragma deleteclass("PolicyPlatform_Document", nofail)
#pragma deleteclass("PolicyPlatform_DocumentId", nofail)
#pragma deleteclass("PolicyPlatform_EnactmentJobMetrics", nofail)
#pragma deleteclass("PolicyPlatform_Rule", nofail)
#pragma deleteclass("PolicyPlatform_Condition", nofail)
#pragma deleteclass("PolicyPlatform_Goal", nofail)
#pragma deleteclass("PolicyPlatform_Variable", nofail)
#pragma deleteclass("PolicyPlatform_PrincipalDocumentBinding", nofail)
