# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import request_pb2 as request__pb2
from . import subscription_pb2 as subscription__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65nvelope.proto\x12\x0b\x41pplication\x1a\rrequest.proto\x1a\x12subscription.proto\x1a\x0c\x63ommon.proto\"\xb7\x01\n\x18\x43lientApplicationMessage\x12?\n\x13\x63lientSingleRequest\x18\x01 \x01(\x0b\x32 .Application.ClientSingleRequestH\x00\x12K\n\x19\x63lientSubscriptionMessage\x18\x02 \x01(\x0b\x32&.Application.ClientSubscriptionMessageH\x00\x42\r\n\x0b\x61pp_message\"\xcd\x02\n\x18ServerApplicationMessage\x12\x41\n\x14serverSingleResponse\x18\x01 \x01(\x0b\x32!.Application.ServerSingleResponseH\x00\x12I\n\x18serverSubscriptionUpdate\x18\x02 \x01(\x0b\x32%.Application.ServerSubscriptionUpdateH\x00\x12M\n\x1aserverSubscriptionResponse\x18\x03 \x01(\x0b\x32\'.Application.ServerSubscriptionResponseH\x00\x12\x45\n\x16serverSubscriptionPing\x18\x04 \x01(\x0b\x32#.Application.ServerSubscriptionPingH\x00\x42\r\n\x0b\x61pp_message\"\x99\x01\n\x13NotificationMessage\x12<\n\x11\x61lertNotification\x18\x01 \x01(\x0b\x32\x1f.Application.Alert.NotificationH\x00\x12\x35\n\x0egenericMessage\x18\x02 \x01(\x0b\x32\x1b.Application.GenericMessageH\x00\x42\r\n\x0b\x61pp_messageB@Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelope_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssg'
  _CLIENTAPPLICATIONMESSAGE._serialized_start=81
  _CLIENTAPPLICATIONMESSAGE._serialized_end=264
  _SERVERAPPLICATIONMESSAGE._serialized_start=267
  _SERVERAPPLICATIONMESSAGE._serialized_end=600
  _NOTIFICATIONMESSAGE._serialized_start=603
  _NOTIFICATIONMESSAGE._serialized_end=756
# @@protoc_insertion_point(module_scope)
