# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp_ims_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15nlp_ims_request.proto\x12\x0b\x41pplication\"X\n\x19ImsSingleUseTokenEnvelope\x12\x12\n\nserialized\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x14\n\x0c\x64\x65ploymentId\x18\x03 \x01(\x0c\"M\n\x1bImsSingleUseTokenGetRequest\x12\x18\n\x10\x63\x61nManageIntents\x18\x01 \x01(\x08\x12\x14\n\x0cmappedUserId\x18\x02 \x01(\tBh\n$com.splunk.mobile.nlp.service.iframeP\x01Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_ims_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.splunk.mobile.nlp.service.iframeP\001Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssg'
  _IMSSINGLEUSETOKENENVELOPE._serialized_start=38
  _IMSSINGLEUSETOKENENVELOPE._serialized_end=126
  _IMSSINGLEUSETOKENGETREQUEST._serialized_start=128
  _IMSSINGLEUSETOKENGETREQUEST._serialized_end=205
# @@protoc_insertion_point(module_scope)
