# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp_splapp_request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18nlp_splapp_request.proto\x12\x0b\x41pplication\"1\n\x18SavedSearchSPLGetRequest\x12\x15\n\rsavedSearchId\x18\x01 \x01(\t\"(\n\x19SavedSearchSPLGetResponse\x12\x0b\n\x03spl\x18\x01 \x01(\t\"/\n\x13SavedSearchMetaData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"3\n\x18SavedSearchesSyncRequest\x12\x17\n\x0fifModifiedSince\x18\x01 \x01(\x03\"\\\n\x19SavedSearchesSyncResponse\x12?\n\x15savedSearchesMetaData\x18\x01 \x03(\x0b\x32 .Application.SavedSearchMetaData\"-\n\x11\x44\x61shboardMetaData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"0\n\x15\x44\x61shboardsSyncRequest\x12\x17\n\x0fifModifiedSince\x18\x01 \x01(\x03\"T\n\x16\x44\x61shboardsSyncResponse\x12:\n\x12\x64\x61shboardsMetaData\x18\x01 \x03(\x0b\x32\x1e.Application.DashboardMetaDataBb\n\x1e\x63om.splunk.nlp.spacebridge.appP\x01Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlp_splapp_request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.splunk.nlp.spacebridge.appP\001Z>cd.splunkdev.com/mobile/spacebridge-golang-protos/splunkcx/ssg'
  _SAVEDSEARCHSPLGETREQUEST._serialized_start=41
  _SAVEDSEARCHSPLGETREQUEST._serialized_end=90
  _SAVEDSEARCHSPLGETRESPONSE._serialized_start=92
  _SAVEDSEARCHSPLGETRESPONSE._serialized_end=132
  _SAVEDSEARCHMETADATA._serialized_start=134
  _SAVEDSEARCHMETADATA._serialized_end=181
  _SAVEDSEARCHESSYNCREQUEST._serialized_start=183
  _SAVEDSEARCHESSYNCREQUEST._serialized_end=234
  _SAVEDSEARCHESSYNCRESPONSE._serialized_start=236
  _SAVEDSEARCHESSYNCRESPONSE._serialized_end=328
  _DASHBOARDMETADATA._serialized_start=330
  _DASHBOARDMETADATA._serialized_end=375
  _DASHBOARDSSYNCREQUEST._serialized_start=377
  _DASHBOARDSSYNCREQUEST._serialized_end=425
  _DASHBOARDSSYNCRESPONSE._serialized_start=427
  _DASHBOARDSSYNCRESPONSE._serialized_end=511
# @@protoc_insertion_point(module_scope)
